### PR TITLE
RRFS CMAQ

### PR DESCRIPTION
**Pull request by zmoon**

### CODE REVIEW

**Comment by zmoon** [comment]
@drnimbusrain do you want this to be merged?

**Comment by zmoon** [comment]
maybe we don't need to since M-M has developed one as well that should eventually get in here. https://github.com/NOAA-CSL/MELODIES-MONET/blob/develop/melodies_monet/new_monetio/rrfs_cmaq.py Or we could merge this one now and later merge the two. @bbakernoaa ?

**Comment by bbakernoaa** [comment]
@zmoon Lets use the one in melodies Monet

**Comment by zmoon** [comment]
#52 added the current MM RRFS-CMAQ reader

**Pull request closed without merging**
