### PR TITLE
Convert pressure variables in RAQMS reader

### PR DESCRIPTION
**Pull request by zmoon**
xref: https://github.com/NOAA-CSL/MELODIES-MONET/pull/99#discussion_r949606252

### CODE REVIEW

**Comment by zmoon** [comment]
@mebruckner @rschwant does this look ok? I based the renames on the ones of @rschwant .

**Comment by mebruckner** [comment]
@zmoon It looks good to me. I can test it and update the raqms melodies-monet commit to reflect this change.

**Comment by zmoon** [comment]
@mebruckner that would be great, thanks

**Comment by rschwant** [comment]
Yes, @zmoon this looks good to me.

**Comment by zmoon** [comment]
@mebruckner I'm going to merge this, if you find an issue we can address in another PR.

**Comment by zmoon** [comment]
CI failures upon merge (though passing before) due to:
* pytest 7.2 release breaking pytest-xdist
  - this has been fixed (https://github.com/pytest-dev/pytest-xdist/issues/246) but conda-forge pytest-xdist is still an old version
* EPA AQS URLs erroring in link check [apparently](https://stackoverflow.com/questions/71603314/ssl-error-unsafe-legacy-renegotiation-disabled) due to their server not supporting OpenSSL 3
  - e.g.  
    ```(tutorial/aqs_pams: line   27) broken    https://aqs.epa.gov/aqsweb/airdata/download_files.html - HTTPSConnectionPool(host='aqs.epa.gov', port=443): Max retries exceeded with url: /aqsweb/airdata/download_files.html (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1129)')))```
  - seems this is affecting the AQS test as well (232e0e4):
    `FAILED tests/test_aqs.py::test_aqs - requests.exceptions.SSLError: HTTPSConnectionPool(host='aqs.epa.gov', port=443): Max retries exceeded with url: /aqsweb/airdata/daily_PM10SPEC_2019.zip (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1131)')))`

**Pull request merged**
