### PR TITLE
GML 100-m ozonesondes

### PR DESCRIPTION
**Pull request by zmoon**
Initial reader for GML ozonesondes, currently only supporting the 100-m files.

Thanks to Owen Cooper (CSL), Bryan Johnson (GML), and Irena for helping with interpretation.

xref: https://github.com/NOAA-CSL/MELODIES-MONET/issues/199

### CODE REVIEW

**Comment by zmoon** [comment]
@bbakernoaa @rschwant I do have some questions about the variables (in the `col_info` defn near the bottom of the file), as I couldn't find a data readme or such.

**Comment by rschwant** [comment]
Let me ask others at NOAA CSL who have used these files a lot whether they have a readme for this dataset. I'll copy you on an email. They are not on GitHub.

**Comment by bbakernoaa** [comment]
Let’s just ask GML…?

**Comment by zmoon** [comment]
Now all of the 11k or so files load except two.

Some questions:

* for selection by site in `add_data()` and `discover_files()`, do we like `place` or `station` or `site` or something else?
* do we like the data variable names (mostly given in `COL_INFO_L100` definition) and long names?

@bbakernoaa @rschwant @iri01 would you be able to take a look?

**Comment by zmoon** [comment]
The altitude diffs are mostly 0.1 (100 m; 99.67%), but not all. For combined files, e.g. for MM, may want to stick to data on those cleaner altitudes (3.5, 3.6, 3.7, ...), maybe storing the surface level data in separate variables. Although, the less-clean altitudes are mostly in the lower troposphere.

From Bryan:
> The first line is the actual elevation then the 100 meter intervals begin for the rest of the flight.  So the spacing will only be different from surface to first interval.

Also, for combined files, note that there are some cases of same launch time/place (e.g. one station launching two at the same time). The flight number can be used to differentiate them.

**Comment by zmoon** [comment]
"University of Rhode Island" should maybe be normalized to "Narragansett, Rhode Island".

And perhaps "Mauna Loa Observatory, Hawaii" to "Hilo, Hawaii"? Seems like it only has 2 soundings, in 2002, and the launch loc isn't that far away.

**Comment by iri01** [comment]
This looks great!
Would it be possible to include humidity in the variables, provided it is a reliable measurement?

On your earlier questions: 

 > * for selection by site in `add_data()` and `discover_files()`, do we like `place` or `station` or `site` or something else?
 
 I like `station` or, if used in other search criteria, either `place` or `location`
 
 > * do we like the data variable names (mostly given in `COL_INFO_L100` definition) and long names?
 
I like:
"o3_mpa" for ozone partial pressure
>    ColInfo("o3_press", "ozone partial pressure", "mPa", "99.90"),

"o3_ppm" for ozone mixing ratio in ppmv
>    ColInfo("o3", "ozone mixing ratio", "ppmv", "99.999"),

"o3_col" for ozone partial column
>    ColInfo("o3_int", "integrated ozone below", "atm-cm", "99.9990")

"o3_du" for ozone total column in DU

**Review by bbakernoaa — APPROVED** [review]

**Review by bbakernoaa — APPROVED** [review]

**Comment by zmoon** [comment]
@bbakernoaa I changed `place` arg to `location` (not `siteid` since a location folder's data may have multiple unique values of 'station'). But then I changed 'station' to 'siteid' in the `add_data()` output for MONETIO-ness.

**Comment by bbakernoaa** [comment]
👍


Barry Baker

National Oceanic and Atmospheric Administration
Air Resources Laboratory
Physical Research Scientist
Chemical Modeling and Emissions Group Leader
NCWCP, R/ARL, Rm. 4204
5830 University Research Court
College Park, Maryland  20740
Phone: ‪(301) 683-1395‬

**Pull request merged**
